### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by karthikkm007** [pirej/kernel#1]
I tried this kernel for compiling AOKP 7.1.2. 32 bit
Every thing Woking except audio.
I used wt88047_defconfig file to compile

After so many searches I found that sound problem exist in kernel source.

So I flashed immune kernel now audio is working fine 

Could you please have a look on this?

Thank you

**Comment by pirej** [comment]
Do you have something like mixer_paths_xxxx.xml not found/missing(when using my caf kernel) in your logs?

**Comment by karthikkm007** [comment]
NOPE

**Comment by karthikkm007** [comment]
Nope but I have logcat please have a look on it
[logcat.txt](https://github.com/pirej/kernel/files/1602796/logcat.txt)

**Comment by pirej** [comment]
Before anything else... WHY are you using this old kernel?
And which branch do you use?

**Comment by karthikkm007** [comment]
OK where is the new branch ?
Could you paste the link here

**Comment by pirej** [comment]
If you want the 32bit branch
https://github.com/redmi2/kernel/commits/nn
And you should omit the last two commits because the camera wont work as is..
But i doubt that it will "fix" the audio issue you are having.

You could try adding another mixer_paths.xml in ststem/etc
And... try renaming the sound-card from "qcom,model = "msm8x16-wt88047-snd-card"; "
in to "qcom,model = "msm8x16-skui-snd-card";  "
in https://github.com/redmi2/kernel/blob/nn/arch/arm/boot/dts/qcom/msm8916-qrd-skum.dtsi

**Comment by karthikkm007** [comment]
thanks
